### ISSUE TITLE
Cannot find module 'debowerify' when installed with the -g option

### ISSUE THREAD

**Issue by constfun** [eugeneware/debowerify#17]
I'd like to install debowerify globally:

```
npm install -g debowerify
```

This doesn't work for some reason:

```
devbox% browserify -t debowerify main.js -o bundle.js
Error: Cannot find module 'debowerify'
```

**Comment by lv7777** [comment]
hi, I get same error and find this.
I really wanted use debowerify via global install.
anyone know how to avoid the error?

**Comment by quarterto** [comment]
Why do you want to globally install debowerify? The only reason you should consider globally installing an npm module is to use its bin everywhere. If you ever want to `require` a module (this includes browserify transforms), you should install it locally (and put it in your package.json so other people can get set up on your modules just by running `npm install`).

**Comment by eugeneware** [comment]
@quarterto is correct. Best practice is to install transforms in the local `node_modules`.

**Comment by lv7777** [comment]
> The only reason you should consider globally installing an npm module is to use its bin everywhere

I want this feature,but I investigate various site, almost people has same opinion with you.
So, I Take a second look at the think.
thanks.
