### ISSUE TITLE
Shouldn't debowerify take package.json's "main" field into account?

### ISSUE THREAD

**Issue by JPGygax68** [eugeneware/debowerify#28]
I have tried to use debowerify on Knockout.js. It didn't work because debowerify does not look at the `main` field of the `package.json` file, which states that the path to the main file is actually `build/output/knockout-latest.js`, and instead falls back to trying just `knockout.js`.

I looked at the code, and the reason for this behavior is that debowerify uses the bower "list paths" command to obtain its paths.

Incidentally, adding a `main` field to `.bower.json` would solve the problem - unfortunately, Knockout doesn't have that field in its `.bower.json` file.

So I guess this brings up a couple of questions:
1. Is it up to a module implementor (or the party packaging that module for bower) to provide the `main` path in `.bower.json`, even when the same information could already be obtained from `package.json`? This may violate the DRY principle - the question is whether `.bower.json` is supposed to _replace_ `package.json` in browser environments, or just _add_ to it.
2. Supposing information from `package.json` really should be taken into account, that leaves the question whether the problem should be fixed in bower itself or in debowerify - or possibly in both ?

**Comment by barroudjo** [comment]
Just to add to that: I have the same issue as JPGygax68.
While I agree that it would be better to use npm for all packages, the fact remains that for frontend development, bower modules are more available than npm modules. And I'd rather not mix npm with bower (that would be a mess), so I only use bower for my dependencies.

In my case with the library iscroll, debowerify can't find the "iscroll.js" file, but there is a package.json where the main is defined. It would be great if debowerify, seeing that the file it's looking for does not exist, read that field and used it.
