### ISSUE TITLE
Incorrectly assuming bower is using current working directory

### ISSUE THREAD

**Issue by kornelski** [eugeneware/debowerify#36]
``` js
bower.commands.install([], {}, {cwd: "/tmp/xxx"})
var browserify = new Browserify();
browserify.transform(require('debowerify'));
```

debowerify calls `bower.commands.list` with the default configuration, which may be incompatible with the configuration that's been used to install components.

I'm creating a web service that builds browserified JS files on-demand, so there can be several bower installations running at the same time, so I can't rely on the globally shared current working directory.

It'd be nice if it was possible to pass configuration or list of modules to debowerify somehow (in my case passing `bowerModules` is preferred, since I have that cached already).

e.g.

``` js
browserify.transform(require('debowerify').create({bowerModules:mymodules}));
```

**Comment by benjamindulau** [comment]
+1

**Comment by ossrapaport** [comment]
+1
And did anyone figure out a way to solve this until a fix is made?
