### ISSUE TITLE
Don't filter files with .es6 extensions

### ISSUE THREAD

**Issue by anicholson** [eugeneware/debowerify#74]
Lots of people use `.es6` as their file extension to explicitly signal which version of ECMAScript they're supporting. But if the entrypoint passed to browserify is such a file, debowerify will ignore it even if it's been transformed through a transpiler first.

**Comment by w4** [comment]
@eugeneware any chance this could be looked into?

**Comment by eugeneware** [comment]
Hi @anicholson - I've fixed this in 7eeabf2f69778a70a1c29cb7772589227c9cc41a and have published it as version `1.5.0`.

**Comment by anicholson** [comment]
I had had a PR for this! :D #75 Glad it's fixed though :)
